import { ObjectField } from "@tinacms/schema-tools";
import React from "react";

export const ANIMATIONS = [
  { value: "none", label: "Нет" },
  { value: "half-pulse", label: "ПульсацияV2" },
  { value: "half-fadeIn", label: "ПоявлениеV2" },
  { value: "half-fadeInDown", label: "Появление внизV2" },
  { value: "half-fadeInDownBig", label: "Появление внизV2 (большое)" },
  { value: "half-zoomIn", label: "УвеличениеV2" },
  { value: "half-slideInDown", label: "Скольжение внизV2" },
  { value: "half-slideInLeft", label: "Скольжение влевоV2" },
  { value: "half-slideInRight", label: "Скольжение вправоV2" },
  { value: "half-slideInUp", label: "Скольжение вверхV2" },
  { value: "bounce", label: "Прыжок" },
  { value: "flash", label: "Вспышка" },
  { value: "pulse", label: "Пульсация" },
  { value: "rubberBand", label: "Резиновая лента" },
  { value: "shakeX", label: "Тряска X" },
  { value: "shakeY", label: "Тряска Y" },
  { value: "headShake", label: "Тряска головой" },
  { value: "swing", label: "Качание" },
  { value: "tada", label: "Тада" },
  { value: "wobble", label: "Колебание" },
  { value: "jello", label: "Желе" },
  { value: "heartBeat", label: "Сердцебиение" },
  { value: "backInDown", label: "Возврат вниз" },
  { value: "backInLeft", label: "Возврат влево" },
  { value: "backInRight", label: "Возврат вправо" },
  { value: "backInUp", label: "Возврат вверх" },
  { value: "backOutDown", label: "Выход вниз" },
  { value: "backOutLeft", label: "Выход влево" },
  { value: "backOutRight", label: "Выход вправо" },
  { value: "backOutUp", label: "Выход вверх" },
  { value: "bounceIn", label: "Прыжок внутрь" },
  { value: "bounceInDown", label: "Прыжок вниз" },
  { value: "bounceInLeft", label: "Прыжок влево" },
  { value: "bounceInRight", label: "Прыжок вправо" },
  { value: "bounceInUp", label: "Прыжок вверх" },
  { value: "bounceOut", label: "Прыжок наружу" },
  { value: "bounceOutDown", label: "Прыжок наружу вниз" },
  { value: "bounceOutLeft", label: "Прыжок наружу влево" },
  { value: "bounceOutRight", label: "Прыжок наружу вправо" },
  { value: "bounceOutUp", label: "Прыжок наружу вверх" },
  { value: "fadeIn", label: "Появление" },
  { value: "fadeInDown", label: "Появление вниз" },
  { value: "fadeInDownBig", label: "Появление вниз (большое)" },
  { value: "fadeInLeft", label: "Появление влево" },
  { value: "fadeInLeftBig", label: "Появление влево (большое)" },
  { value: "fadeInRight", label: "Появление вправо" },
  { value: "fadeInRightBig", label: "Появление вправо (большое)" },
  { value: "fadeInUp", label: "Появление вверх" },
  { value: "fadeInUpBig", label: "Появление вверх (большое)" },
  { value: "fadeInTopLeft", label: "Появление сверху слева" },
  { value: "fadeInTopRight", label: "Появление сверху справа" },
  { value: "fadeInBottomLeft", label: "Появление снизу слева" },
  { value: "fadeInBottomRight", label: "Появление снизу справа" },
  { value: "fadeOut", label: "Исчезновение" },
  { value: "fadeOutDown", label: "Исчезновение вниз" },
  { value: "fadeOutDownBig", label: "Исчезновение вниз (большое)" },
  { value: "fadeOutLeft", label: "Исчезновение влево" },
  { value: "fadeOutLeftBig", label: "Исчезновение влево (большое)" },
  { value: "fadeOutRight", label: "Исчезновение вправо" },
  { value: "fadeOutRightBig", label: "Исчезновение вправо (большое)" },
  { value: "fadeOutUp", label: "Исчезновение вверх" },
  { value: "fadeOutUpBig", label: "Исчезновение вверх (большое)" },
  { value: "fadeOutTopLeft", label: "Исчезновение сверху слева" },
  { value: "fadeOutTopRight", label: "Исчезновение сверху справа" },
  { value: "fadeOutBottomRight", label: "Исчезновение снизу справа" },
  { value: "fadeOutBottomLeft", label: "Исчезновение снизу слева" },
  { value: "flip", label: "Переворот" },
  { value: "flipInX", label: "Переворот по X" },
  { value: "flipInY", label: "Переворот по Y" },
  { value: "flipOutX", label: "Переворот наружу по X" },
  { value: "flipOutY", label: "Переворот наружу по Y" },
  { value: "lightSpeedInRight", label: "Вправо с эффектом лёгкости" },
  { value: "lightSpeedInLeft", label: "Влево с эффектом лёгкости" },
  { value: "lightSpeedOutRight", label: "Вправо с эффектом лёгкости (исчезновение)" },
  { value: "lightSpeedOutLeft", label: "Влево с эффектом лёгкости (исчезновение)" },
  { value: "rotateIn", label: "Вращение внутрь" },
  { value: "rotateInDownLeft", label: "Вращение внутрь вниз-влево" },
  { value: "rotateInDownRight", label: "Вращение внутрь вниз-вправо" },
  { value: "rotateInUpLeft", label: "Вращение внутрь вверх-влево" },
  { value: "rotateInUpRight", label: "Вращение внутрь вверх-вправо" },
  { value: "rotateOut", label: "Вращение наружу" },
  { value: "rotateOutDownLeft", label: "Вращение наружу вниз-влево" },
  { value: "rotateOutDownRight", label: "Вращение наружу вниз-вправо" },
  { value: "rotateOutUpLeft", label: "Вращение наружу вверх-влево" },
  { value: "rotateOutUpRight", label: "Вращение наружу вверх-вправо" },
  { value: "hinge", label: "Петля" },
  { value: "jackInTheBox", label: "Коробка с Джеком" },
  { value: "rollIn", label: "Сворачивание" },
  { value: "rollOut", label: "Разворачивание" },
  { value: "zoomIn", label: "Увеличение" },
  { value: "zoomInDown", label: "Увеличение снизу" },
  { value: "zoomInLeft", label: "Увеличение слева" },
  { value: "zoomInRight", label: "Увеличение справа" },
  { value: "zoomInUp", label: "Увеличение сверху" },
  { value: "zoomOut", label: "Уменьшение" },
  { value: "zoomOutDown", label: "Уменьшение вниз" },
  { value: "zoomOutLeft", label: "Уменьшение влево" },
  { value: "zoomOutRight", label: "Уменьшение вправо" },
  { value: "zoomOutUp", label: "Уменьшение сверху" },
  { value: "slideInDown", label: "Скольжение вниз" },
  { value: "slideInLeft", label: "Скольжение влево" },
  { value: "slideInRight", label: "Скольжение вправо" },
  { value: "slideInUp", label: "Скольжение вверх" },
  { value: "slideOutDown", label: "Скольжение наружу вниз" },
  { value: "slideOutLeft", label: "Скольжение наружу влево" },
  { value: "slideOutRight", label: "Скольжение наружу вправо" },
  { value: "slideOutUp", label: "Скольжение наружу вверх" }
];

export type animationFieldType = {
  type?: string | null,
  isScroll?: boolean | null,
  speed?: string | null
  showOnce?: boolean  | null;
}

export const ANIMATION_SCHEMA: ObjectField = {
  name: "animation",
  label: "Анимация",
  type: "object",
  fields: [
    {
      name: "type",
      label: "Тип",
      type: "string",
      options: ANIMATIONS,
      searchable: true
    },
    {
      type: "boolean",
      name: "isScroll",
      label: "Привязано к скроллу"
    },
    {
      type: "boolean",
      name: "_",
      ui: {
        component: () => {
          return <><h4 className="font-bold mt-4" style={{whiteSpace: "pre-line"}}> Настройки для временных анимаций (не по скроллу) </h4></>;
        }
      }
    },
    {
      type: "string",
      name: "speed",
      label: "Скорость",
      options: [
        { value: "slower", label: "0.33x" },
        { value: "slow", label: "0.5x" },
        { value: "1x", label: "1x" },
        { value: "fast", label: "1.2x" },
        { value: "faster", label: "2x" },
      ]
    },
    {
      type: "boolean",
      name: "showOnce",
      label: "Показать только один раз",
    }
  ]
};