query pageQuery {
  ...LayoutQueryFragment
  projectsConnection {
      edges {
        node {
          title
          titleMap
          titleList
          date
          hashtags
          heroImg
          type
          _sys {
            filename
          }
        }
      }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query projectsQuery($relativePath: String!) {
  ...LayoutQueryFragment
  projects(relativePath: $relativePath) {
    ...ProjectsParts
  }
}
